### Modelling HDB Resale Price

In this project we explore the dataset "Resale flat prices based on registration date from Jan-2017 onwards" by HDB. It is an actively-updated dataset.

However, in this analysis I will conduct data exploration, cleaning, preprocessing, and preliminary statistical analysis on a static version obtain on 20 July 2026.

The main aim of this project is to model the resale price of HDBs throughout the years, based on various predictors. With such a model, we will be able to answer questions like "How much should a certain HDB cost?" "How much will a certain HDB appreciate over the years?"

In [ ]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
from pathlib import Path

resale_data_path = Path() / "data" / "resale_flat_prices_20260720.csv" # update path as necessary
ResalePrices = pd.read_csv(resale_data_path)

In [4]:
ResalePrices.head()

,month,town,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,lease_commence_date,remaining_lease,resale_price
0,2017-01,ANG MO KIO,2 ROOM,406,ANG MO KIO AVE 10,10 TO 12,44.0,Improved,1979,61 years 04 months,232000.0
1,2017-01,ANG MO KIO,3 ROOM,108,ANG MO KIO AVE 4,01 TO 03,67.0,New Generation,1978,60 years 07 months,250000.0
2,2017-01,ANG MO KIO,3 ROOM,602,ANG MO KIO AVE 5,01 TO 03,67.0,New Generation,1980,62 years 05 months,262000.0
3,2017-01,ANG MO KIO,3 ROOM,465,ANG MO KIO AVE 10,04 TO 06,68.0,New Generation,1980,62 years 01 month,265000.0
4,2017-01,ANG MO KIO,3 ROOM,601,ANG MO KIO AVE 5,01 TO 03,67.0,New Generation,1980,62 years 05 months,265000.0

In [6]:
ResalePrices.dtypes

month                      str
town                       str
flat_type                  str
block                      str
street_name                str
storey_range               str
floor_area_sqm         float64
flat_model                 str
lease_commence_date      int64
remaining_lease            str
resale_price           float64
dtype: object

In [5]:
ResalePrices.describe()

       floor_area_sqm  lease_commence_date  resale_price
count   235808.000000        235808.000000  2.358080e+05
mean        96.686015          1996.573475  5.323648e+05
std         24.016888            14.370177  1.909245e+05
min         31.000000          1966.000000  1.400000e+05
25%         81.000000          1985.000000  3.900000e+05
50%         93.000000          1997.000000  5.000000e+05
75%        112.000000          2012.000000  6.400000e+05
max        366.700000          2022.000000  1.728000e+06